# Generated by Django 4.1.5 on 2023-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('book_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('isbn', models.TextField(db_column='ISBN')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('price', models.BigIntegerField()),
                ('star', models.FloatField()),
                ('category', models.TextField()),
                ('img', models.TextField()),
            ],
            options={
                'db_table': 'ebook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('join_date', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Read',
            fields=[
                ('r_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_read',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Wanted',
            fields=[
                ('w_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_wanted',
                'managed': False,
            },
        ),
    ]
