# Generated by Django 4.1.5 on 2023-03-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_rank', models.IntegerField()),
                ('isbn_n', models.CharField(max_length=100)),
                ('isbn_m', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('rank_total', models.FloatField()),
                ('commentary_total', models.FloatField()),
                ('rank_total_nz', models.FloatField()),
                ('commentary_total_nz', models.FloatField()),
                ('final_score_nz', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
